### PR TITLE
Make it so you can set a default value

### PR DESCRIPTION
**Pull request by roelvanhoof**
Make _value public and rename it to searchValue so you can set a default value by providing search-value="default value" to the paper-input-place element.

I use this in my own site because I use geoip to determine visitors city by ip and default that into the paper-input-place

### CODE REVIEW

**Comment by mlisook** [comment]
I must not understand this use case properly.  How does setting a default `searchValue` differ from setting `value`  to detected initial location?

**Comment by roelvanhoof** [comment]
In my experience setting the value needs an object with all the data inside it valid, so a search but also a place_id and latLng. All i want to do is just set a default search string and let the maps api find the corresponding place and latlng.

Maybe I am not getting something and it should just be possible by setting 'value', could you show me an example?

**Comment by mlisook** [comment]
Thanks, I understand better now.

I added a demo scenario with setting just the search to the [project demo page](https://mlisook.github.io/paper-input-place/) while I was updating that page today. Take a look at the 4th demo, "Initialize just place name" and see if it applies.  Of course I recognize it may not.

``` HTML
<paper-input-place value="{{val}}" place="{{place}}" hide-error
    api-key="[[apiKey]]" label="Pick a place, any place">
    </paper-input-place>
```

``` JS
this.val = {  search: "Ibiza, Balearic Islands, Spain" };
```

I am not opposed to this PR, I'd just like to be certain that we're actually adding a new capability.

Thanks again.

**Comment by roelvanhoof** [comment]
You are right, that does work, don't know how i missed that one, thanks!

**Pull request closed without merging**
