### PR TITLE
Added a property to hide the invalid state and error message

### PR DESCRIPTION
**Pull request by roelvanhoof**
I needed this for my own project, maybe it's not the best solution but I am still learning (web components) polymer

### CODE REVIEW

**Comment by mlisook** [comment]
Looks like a good feature to me!

**Comment by mlisook** [comment]
Oh, we need a commit tagged with the new version number or the updated code won't be on bower.

**Comment by roelvanhoof** [comment]
can i create this tag or should you? I have already created it on my forked repo but i think i did that after i did the pull request

**Comment by mlisook** [comment]
I found an error, _not_ related to this PR - see [issue 4](https://github.com/mlisook/paper-input-place/issues/4), and fixed it.  So there's now a new higher tag, 1.0.3 which has been committed.  Any new bower install or update will now include the feature you added.

**Pull request merged**
